vocabulary = {
	"so":"so, thus",
	"sprechen":"to speak",
	"Herr, der":"the Man, Mr ..., the Lord",
	"wegen":"because of",
	"drei":"three",
	"Freveltat, die":"heinous deed",
	"von":"of",
	"vier":"four",
	"zurucknehmen":"to take back",
	"ich":"I",
	"es":"it",
	"nicht":"not",
	"weil":"because",
	"sie (nom,pl)":"they",
	"Gebein, das":"skeleton, bones, mortal remains",
	"Konig,der":"king",
	"zu":"to",
	"Kalk, der":"line,calcium",
	"verbrennen":"to burn,to incinerate,to cremate",
	"haben":"to have",
	"loslassen":"to let go of",
	"Feuer,das":"fire",
	"wider":"against",
	"dass":"that",
	"Palast,der":"palace",
	"verzehren":"to devour, to consume",
	"und":"and",
	"umkommen":"to die,to perish",
	"bei":"by,with,doing",
	"Kreigslarm":"noise of war",
	"Schall, der":"sound",
	"Posaune, die":"trumpet",
	"vertilgen":"to destroy,to eradicate",
	"Herrscher, der":"ruler",
	"aus":"out of,from",
	"sein":"his, its",
	"Mitte,die":"midst,middle",
	"mit":"with",
	"ihm":"him",
	"toten":"to kill",
	"Furst, der":"prince,ruler",
	"Gesetz, das":"las",
	"verwerfen":"to reject",
	"Satzung":"statutes",
	"halten":"to hold, to keep",
	"ihr (poss pronoun)":"her,hers,its,their,theirs",
	"Luge, die":"lie",
	"d.h. (das Heisst)":"that is",
	"Gotze, der":"idol",
	"irrefurhen":"to lead astray",
	"denen":"which",
	"schon":"already",
	"Vater,der":"father",
	"folgen":"to follow"

}